videoId: "Oq3w3jed03o"
title: "Cardiology Stent Deployment Procedure"
description: ""
thumbnailUrl: "https://img.youtube.com/vi/Oq3w3jed03o/maxresdefault.jpg"
duration: "0:40"
durationSeconds: "40"
publishedAt: "2022-04-30T12:42:02Z"
updatedAt: "2025-12-26T21:21:58.370Z"
category: "ECG Education"
