videoId: "xDRUJ_UF_qU"
title: "Digoxin: ICU Applications, Mechanism of Action, Contraindications, & Drug Dosing Guide"
description: "Hello, welcome to @ecgkid . Today we will discuss a very important cardiac drug - digoxin. We will discuss its uses in the ICU, mechanism of action, and detailed drug dosing. Whether you're a medical professional, student, or simply curious about this medication, this video will provide you with a thorough insight into the world of Digoxin. #digoxin #cardiachealth #icu TIMESTAMP: 0:00 Intro 0:21 Case presentation 1:28 What is Digoxin? 1:46 Uses in ICU/CCU 2:18 Mechanism of action 3:22 Dosage & ..."
thumbnailUrl: "https://img.youtube.com/vi/xDRUJ_UF_qU/maxresdefault.jpg"
duration: "5:28"
durationSeconds: "328"
publishedAt: "2023-12-02T15:22:17Z"
updatedAt: "2025-12-26T21:21:50.872Z"
category: "Case Studies"
